### ISSUE TITLE
Type cast 

### ISSUE THREAD

**Issue by JqyModi** [pro100andrey/lame#1]
How do I turn Swift or OC objects into C arrays (char * argv[]), for example UnsafePointer<sox_format_t> to UnsafePointer<UnsafeMutablePointer<Int8>?>?

**Comment by pro100andrey** [comment]
@JqyModi, hello, could you provide code example or additional info?

**Comment by JqyModi** [comment]
DemoURL：https://github.com/JqyModi/Swift_Sox
I plan to use sox to process audio files, but I don't know how to convert the objects obtained by Swift into the array pointer received by C, the code is located in the SRC folder, I have the place of the comment, comment: // how to convert sourceRead to UnsafePointer<unsafemutablepointer<int8>?>?

**Comment by JqyModi** [comment]
@pro100andrey

**Comment by pro100andrey** [comment]
@JqyModi 

Like this:

```
let argv = UnsafePointer(sourceRead.withMemoryRebound(to: Int8.self, capacity: MemoryLayout<sox_format_t>.size) { $0 })
```
