### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by StasMalinovsky** [pro100andrey/lame#11]
**Describe the bug**
There is a bunch of warnings during compilation. The project target is iOS 13. Xcode 14.3.1.
For example:
ld: warning: object file (/Users/user/Library/Developer/Xcode/DerivedData/project-bolrfaqprskbdlbtnqgiupztkgqw/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/lame/lame.framework/lame(VbrTag.o)) was built for newer iOS version (16.4) than being linked (13.0)

**Expected behavior**
No warnings

**Screenshots**
![Warnings](https://github.com/pro100andrey/lame/assets/9890652/543fdd3d-7032-428e-b829-6a8e2922c863)

**Comment by pro100andrey** [comment]
Fixed  v1.2.0
