### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by zionun** [pro100andrey/lame#15]
Hello,
thank you for this framework.

Is there any chance this could be released through Swift Package Manager?

**Comment by pro100andrey** [comment]
Hello @zionun ,

Thank you for your suggestion. I will definitely look into releasing this through Swift Package Manager in the near future.

Best regards.

**Comment by pro100andrey** [comment]
@zionun, done. Try adding the package by following these steps:

Open your project in Xcode.
Go to File -> Add Package Dependency....
Enter the URL: https://github.com/pro100andrey/lame.
Select version 1.2.1.
Follow the prompts to complete the addition of the package.

Best regards.

**Comment by zionun** [comment]
Oh wow! That was super fast! Thank you very much!
Unfortunately I'm experiencing an issue; when I build and run I get this error:
`Failed to load Info.plist from bundle at path /Users/***/data/Library/Caches/com.apple.mobile.installd.staging/temp.rh90Lb/extracted/test.app/Frameworks/lame.framework; Extra info about "/Users/***/data/Library/Caches/com.apple.mobile.installd.staging/temp.rh90Lb/extracted/test.app/Frameworks/lame.framework/Info.plist": Couldn't stat /Users/***/data/Library/Caches/com.apple.mobile.installd.staging/temp.rh90Lb/extracted/test.app/Frameworks/lame.framework/Info.plist: No such file or directory`

I tried on a brand new project, adding only lame package, and I still get the error.

**Comment by zionun** [comment]
I'm checking all other packages I installed on the main project and none of them contains the Info.plist 🤔

**Comment by pro100andrey** [comment]
Hi @zionun,

Could you please provide a test project?

**Comment by pro100andrey** [comment]
@zionun, Could you please try clean cache, and derived data?

**Comment by pro100andrey** [comment]
<img width="359" alt="Screenshot 2024-07-05 at 11 17 36" src="https://github.com/pro100andrey/lame/assets/46396672/a8ca33ef-71ce-4720-b24a-c7c98a395087">

**Comment by zionun** [comment]
Unfortunately resetting package caches and cleaning the build folder didn't help.
Here is a test project:  [LameTest.zip](https://github.com/user-attachments/files/16107072/LameTest.zip)
It's an empty project with just the lame package

**Comment by pro100andrey** [comment]
Works fine for me
<img width="1075" alt="Screenshot 2024-07-05 at 11 22 40" src="https://github.com/pro100andrey/lame/assets/46396672/f7e33861-c155-4fcd-b991-208b91b8d2f9">

**Comment by pro100andrey** [comment]
@zionun, try - System settings ->  General -> Storage-> Developer -> clean Xcode cache

**Comment by zionun** [comment]
No luck :(
Anyway, it builds successfully for me too. The problem is when I build and run on a simulator.

**Comment by pro100andrey** [comment]
@zionun I need more time for investigating this issue

**Comment by pro100andrey** [comment]
@zionun could you please check 1.2.2 version

**Comment by zionun** [comment]
> @zionun could you please check 1.2.2 version

it worked! thank you 🙏🏻

**Comment by pro100andrey** [comment]
Nice!

**Comment by zionun** [comment]
Hello,
un update on this. I tried sending our app to the App Store but it gave me this error:

![error](https://github.com/user-attachments/assets/4d6733ac-ddcc-4fed-91f4-657d39865475)

**Comment by pro100andrey** [comment]
Hi @zionun, I need some time to fix this.

**Comment by pro100andrey** [comment]
@zionun please check 1.2.3 version

**Comment by pro100andrey** [comment]
@zionun There is a problem - I can't check these errors, so I need your help.

**Comment by zionun** [comment]
@pro100andrey Thank you. No problem, I will check with my next upload to the App Store which will be probably tomorrow.

**Comment by pro100andrey** [comment]
@zionun Thank you, I will be waiting for your response.

**Comment by zionun** [comment]
Hello.
It's giving me this error now, with 1.2.4.

![error](https://github.com/user-attachments/assets/48d6127c-c68b-4aa5-b888-b935b4b0d7b5)

**Comment by pro100andrey** [comment]
Hi @zionun could you please check 1.2.5 version?

Thanks!

**Comment by zionun** [comment]
@pro100andrey same error 😞

**Comment by pro100andrey** [comment]
@zionun could you provide information about your minimum deployment target?

**Comment by zionun** [comment]
my minimum deployment target is 15.0

**Comment by pro100andrey** [comment]
@zionun could you please check 1.2.6 version?

**Comment by zionun** [comment]
It worked! Thank you

**Comment by pro100andrey** [comment]
Thank you!
