### ISSUE TITLE
Merge multiple mp3 files into one mp3

### ISSUE THREAD

**Issue by areeudh-q** [pro100andrey/lame#16]
**Is your feature request related to a problem? Please describe.**
First of all thanks for the code. I would like to know if this third party library can h merge multiple mp3 audio

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pro100andrey** [comment]
Hi @areeudh-q, To merge multiple MP3 files into one MP3, you need to use FFmpeg. like [FFmpeg-iOS](https://github.com/kewlbear/FFmpeg-iOS)

This will concatenate two mp3 files, and the resulting metadata will be that of the first file:

``` bash
ffmpeg -i "concat:file1.mp3|file2.mp3" -acodec copy output.mp3
```

```swift
import FFmpegSupport

ffmpeg(["ffmpeg", "-i", "concat:file1.mp3|file2.mp3", "-acodec", "copy", "output.mp3"])
```

Thanks!
