### ISSUE TITLE
File decoding

### ISSUE THREAD

**Issue by rastaman111** [pro100andrey/lame#18]
Hello! 
How can I know in advance that a file has Lame encoding?

I have a file with lame 3.93. 
Did I understand correctly that after decoding I will be able to get the metadata in normal form, without hieroglyphs?

**Comment by pro100andrey** [comment]
Hi @rastaman111,
> How can I know in advance that a file has Lame encoding?
 
You can check if a file uses LAME encoding with tools that analyze audio headers, such as [ffprobe](https://swiftpackageindex.com/Ponyboy47/FFProbe)

``` bash
ffprobe -i yourfile.mp3 -hide_banner
```
> Did I understand correctly that after decoding I will be able to get the metadata in normal form, without hieroglyphs?

Yes, after decoding the MP3 (e.g., to WAV or FLAC), you should get readable metadata. However:

- "Hieroglyphs" in metadata usually occur due to:
  - Encoding mismatch (e.g., UTF-8 vs. ISO-8859-1).
  - Corrupted or non-standard tags.

MP3s can store metadata in ID3 tags (ID3v1, ID3v2), and older tags (like ID3v1) might not fully support Unicode. LAME 3.93 should handle ID3v2, which supports Unicode.

Let me know if I understood you correctly and answered your questions.

Thanks.

**Comment by rastaman111** [comment]
and who knows how I can check what encoding a file has using native methods?

**Comment by pro100andrey** [comment]
I'm not sure, but try this:

`https://developer.apple.com/documentation/avfoundation/avmetadataitem/1389374-metadataitems`
```swift
import Foundation
import AVFoundation

func readMP3Metadata(from url: URL) {
    let asset = AVAsset(url: url)
    
    for metadataItem in asset.commonMetadata {
        if let key = metadataItem.commonKey?.rawValue, 
           let value = metadataItem.value {
            print("\(key): \(value)")
        }
    }
}


if let fileURL = Bundle.main.url(forResource: "example", withExtension: "mp3") {
    readMP3Metadata(from: fileURL)
} else {
    print("not found")
}
```
![MP3filestructure svg](https://github.com/user-attachments/assets/7c971938-e6c4-4bb7-b1ce-3a9d5d050030)

`https://en.wikipedia.org/wiki/MP3`

As a last resort, you can study the structure of an MP3 file and write your own function to read the metadata. like this example )
``` swift
import Foundation

struct ID3v1Tag {
    var title: String
    var artist: String
    var album: String
    var year: String
    var comment: String
    var genre: UInt8
}

func readID3v1Tag(from url: URL) -> ID3v1Tag? {
    guard let fileHandle = try? FileHandle(forReadingFrom: url) else {
        print("Failed to open the file.")
        return nil
    }
    
    // Move to the last 128 bytes where the ID3v1 tag is located
    fileHandle.seekToEndOfFile()
    let fileSize = fileHandle.offsetInFile
    guard fileSize >= 128 else {
        print("The file is too small to contain ID3v1 tags.")
        return nil
    }
    fileHandle.seek(toFileOffset: fileSize - 128)
    
    // Read the last 128 bytes
    let tagData = fileHandle.readData(ofLength: 128)
    fileHandle.closeFile()
    
    // Check if the first three bytes are "TAG"
    guard let tagString = String(data: tagData.prefix(3), encoding: .utf8), tagString == "TAG" else {
        print("ID3v1 tags not found.")
        return nil
    }
    
    // Extract fields from the ID3v1 tag
    let title = extractString(from: tagData, range: 3..<33)
    let artist = extractString(from: tagData, range: 33..<63)
    let album = extractString(from: tagData, range: 63..<93)
    let year = extractString(from: tagData, range: 93..<97)
    let comment = extractString(from: tagData, range: 97..<127)
    let genre = tagData[127]
    
    return ID3v1Tag(title: title, artist: artist, album: album, year: year, comment: comment, genre: genre)
}

func extractString(from data: Data, range: Range<Int>) -> String {
    let subdata = data.subdata(in: range)
    return String(data: subdata, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
}

// Example usage:
if let fileURL = Bundle.main.url(forResource: "example", withExtension: "mp3") {
    if let tag = readID3v1Tag(from: fileURL) {
        print("Title: \(tag.title)")
        print("Artist: \(tag.artist)")
        print("Album: \(tag.album)")
        print("Year: \(tag.year)")
        print("Comment: \(tag.comment)")
        print("Genre: \(tag.genre)")
    }
} else {
    print("File not found.")
}
```

**Comment by pro100andrey** [comment]
I will close this issue because the answers to your questions can be easily found online. Please feel free to reach out if you need further clarification or assistance.

Thanks.
