### ISSUE TITLE
Issue with i386

### ISSUE THREAD

**Issue by rafagan** [pro100andrey/lame#2]
The lame.framework is not working in simulators using Xcode 12. The following error occurs:

`The linked and embedded framework 'lame.framework' is missing one or more architectures required by this target: i386.`

Any help?

**Comment by pro100andrey** [comment]
Hi @rafagan, could you provide project example? Thanks.

**Comment by rafagan** [comment]
Just create an empty project and try to run in iOS simulator with the framework set

**Comment by pro100andrey** [comment]
Hi @rafagan, Example project is updated, check it.
