### ISSUE TITLE
M1 Macbook Pro: wrong architecture

### ISSUE THREAD

**Issue by YahiaRagae** [pro100andrey/lame#3]
Hi, 

Thanks a lot for the effort in that library, 

I'm facing the below issue with the new M1 machine, 

In project/Pods/lame/lame.framework/lame(VbrTag.o), building for iOS Simulator, but linking in object file (/project/Pods/lame/lame.framework/lame(VbrTag.o)) built for iOS, file '/project/Connect.Valuations.iOS/Pods/lame/lame.framework/lame' for architecture arm64

any idea ?

**Comment by pro100andrey** [comment]
Hi @YahiaRagae. I need more time for investigate this issue.
Could you please check https://developer.apple.com/forums/thread/657913, maybe it help for you.

Thanks.

**Comment by pro100andrey** [comment]
Hi, fixed in 1.0.1

Thanks!
