### ISSUE TITLE
Support for arm64 based simulators

### ISSUE THREAD

**Issue by MMise** [pro100andrey/lame#8]
At the moment, this package does not support arm64 based simulators "out of the box".

Steps to reproduce:
1. Clone this repo
2. Open the 'Example' project
3. Select simulator as the target (iPhone 14 for example)

The following error occurs:
`ld: in /Users/mikko/Dev/lame/Example/Pods/lame/lame.framework/lame(VbrTag.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/mikko/Dev/lame/Example/Pods/lame/lame.framework/lame' for architecture arm64`

This can be fixed by setting `Build Active Architecture Only` to `No` and setting `Excluded Architectures -> Any iOS Simulator SDK` to `arm64` in both the `Example` and `Pods` projects

However, this is not a viable solution as the Apple Silicon Macs run simulators as arm64 by default. Using the fix above in my own project causes other errors for example.

**Comment by StasMalinovsky** [comment]
Are any updates planning here?

**Comment by pro100andrey** [comment]
Hi all, I will try fix it as soon as possible, thanks!

**Comment by pro100andrey** [comment]
hi All, fixed in 1.0.1

Thanks!
